var userName = prompt("what is your first name")
var lastName = prompt("what isyour last name")
var age = prompt("how old are you")
console.log ("nice to meet you" + userName + lastName)
console.log("you are" + age + "years old")